name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout func-helpers library
        uses: actions/checkout@v4
        with:
          repository: crimaniak/func-helpers
          path: func-helpers

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build and install library
        run: mvn -f func-helpers/pom.xml install

      - name: Run tests
        run: mvn -B test
